In [1]:
import pandas as pd

In [11]:
df = pd.read_csv('Student1.csv')

In [12]:
df

   Student   Age  Marks        City
0  arsalan  23.0     35      Lahore
1    adeel  55.0     88   islamabad
2      Ali  78.0     56      gujrat
3    Afnan   NaN     43         NaN
4     abid   NaN     33  rawalpindi

In [13]:
df.shape

(5, 4)

In [14]:
df.columns

Index(['Student', 'Age', 'Marks', 'City'], dtype='str')

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  5 non-null      str
 1   Age      3 non-null      float64
 2   Marks    5 non-null      int64
 3   City     4 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 288.0 bytes

In [17]:
df.describe()

             Age      Marks
count   3.000000   5.000000
mean   52.000000  51.000000
std    27.622455  22.572107
min    23.000000  33.000000
25%    39.000000  35.000000
50%    55.000000  43.000000
75%    66.500000  56.000000
max    78.000000  88.000000

In [20]:
df.head()

   Student   Age  Marks        City
0  arsalan  23.0     35      Lahore
1    adeel  55.0     88   islamabad
2      Ali  78.0     56      gujrat
3    Afnan   NaN     43         NaN
4     abid   NaN     33  rawalpindi

In [25]:
df['Student']

0    arsalan
1      adeel
2        Ali
3      Afnan
4       abid
Name: Student, dtype: str

In [27]:
df[[ 'Age','Marks','City']]

    Age  Marks        City
0  23.0     35      Lahore
1  55.0     88   islamabad
2  78.0     56      gujrat
3   NaN     43         NaN
4   NaN     33  rawalpindi

In [29]:
df.loc[2:2]

  Student   Age  Marks    City
2     Ali  78.0     56  gujrat

In [32]:
df[df['Marks']<40]

   Student   Age  Marks        City
0  arsalan  23.0     35      Lahore
4     abid   NaN     33  rawalpindi

In [35]:
df.isnull()

   Student    Age  Marks   City
0    False  False  False  False
1    False  False  False  False
2    False  False  False  False
3    False   True  False   True
4    False   True  False  False

In [42]:
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [43]:
df

   Student   Age  Marks        City
0  arsalan  23.0     35      Lahore
1    adeel  55.0     88   islamabad
2      Ali  78.0     56      gujrat
3    Afnan  52.0     43         NaN
4     abid  52.0     33  rawalpindi

In [46]:
df["City"]=df["City"].fillna(df["City"].mode())

In [45]:
df

   Student   Age  Marks        City
0  arsalan  23.0     35      Lahore
1    adeel  55.0     88   islamabad
2      Ali  78.0     56      gujrat
3    Afnan  52.0     43  rawalpindi
4     abid  52.0     33  rawalpindi

In [47]:
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x>=50 else "Fail")

In [48]:
df

   Student   Age  Marks        City Result
0  arsalan  23.0     35      Lahore   Fail
1    adeel  55.0     88   islamabad   Pass
2      Ali  78.0     56      gujrat   Pass
3    Afnan  52.0     43  rawalpindi   Fail
4     abid  52.0     33  rawalpindi   Fail